# Generated by Django 4.0 on 2024-02-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_datetime',
        ),
    ]
