# Generated by Django 4.0 on 2024-03-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_session_end_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(max_length=50)),
                ('classification_code', models.CharField(max_length=10)),
                ('classification_description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='athlete',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.classification'),
        ),
    ]
