# Generated by Django 4.0 on 2024-03-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_classification_classification_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('O', 'Other')], max_length=1),
        ),
    ]
