# Generated by Django 4.0 on 2024-03-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_athlete_birth_date_alter_session_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_time', 'stage', 'gender')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('day', 'time')},
        ),
        migrations.RemoveField(
            model_name='session',
            name='gender',
        ),
    ]
